# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Mocha Tests

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Setup Environment
      run: |
        npm ci
        sudo apt install python3-pip -y
        pip3 install pandas

    - name: Run tests
      run: |
        npm test
        python3 python/test_read_data_unittest.py
